### ISSUE TITLE
Race Condition in Shutdown Process

### ISSUE THREAD

**Issue by axelbodo** [avtc/GracefullShutdown#1]
Due to using 2 variables (stopping and pending requests) there is a race condition (though low chance) between the OnStopping and the Invoke, furthermore I would use MemoryBarrier for both the stopping and pending request variable like in this scratch, these will ensure proper read/write ordering in multiprocessor environments:
`        private class GracefullShutdown
        {
            RequestDelegate upstream;
            bool isStopping;
            int pendingRequests;

            public GracefullShutdown(RequestDelegate upstream, IApplicationLifetime lifetime)
            {
                this.upstream = upstream;
                lifetime.ApplicationStopping.Register(ApplicationStopping);
            }

            public async Task Invoke(HttpContext context)
            {
                if(isStopping)
                {
                    context.Response.StatusCode = 500;
                    await context.Response.WriteAsync("Application is stopping");
                    return;
                }
                Interlocked.Increment(ref pendingRequests);
                try
                {
                    //this ammandmend is for solving the race condition due to using two variables (pendngRequests and isStopping) for shutdown handling
                    Interlocked.MemoryBarrier();
                    if(isStopping)
                    {
                        context.Response.StatusCode = 500;
                        await context.Response.WriteAsync("Application is stopping");
                        return;
                    }
                    await upstream.Invoke(context);
                }
                finally
                {
                    Interlocked.Decrement(ref pendingRequests);
                }
            }

            private void ApplicationStopping()
            {
                isStopping = true;
                Interlocked.MemoryBarrier();
                while (pendingRequests > 0)
                {
                    Interlocked.MemoryBarrier();
                    Thread.Sleep(1000);
                }
            }
        }
`

**Comment by avtc** [comment]
State is extracted, made thread safe and registered as singleton.
0a17b9f29cc2c2c876a15f28f5b85e8c6a76df4f
Published as 1.0.1

**Comment by axelbodo** [comment]
After a while :). sorry.
